(dotimes (i 100)
  ; 局所変数の定義
  (let ((num (+ i 1)))
    (if (= 0 (mod num 3))
      (format t "Fizz"))
    (if (= 0 (mod num 5))
      (format t "Buzz"))
    (if (and (not (= 0 (mod num 5)))
             (not (= 0 (mod num 3))))
      (format t "~a" num))
    (format t " " )))
